version: '2.25'

services:
  rosmaster:
    build:
      context: .
      dockerfile: docker/Dockerfile.main
    container_name: rosmaster
    hostname: rosmaster
    networks:
      - rosdocker
    ports:
      - "11311:11311"
    command: roscore

  main:
    build:
      context: .
      dockerfile: docker/Dockerfile.main
    container_name: task_manager
    hostname: task_manager
    volumes:
      - ./ws:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
    networks:
      - rosdocker
    privileged: true
    devices:
      - /dev/video0:/dev/video0
    environment:
      - "ROS_HOSTNAME=task_manager"
      - "ROS_MASTER_URI=http://rosmaster:11311"
      - DISPLAY=${DISPLAY}
      - LOCAL_USER_ID=id -u ${USER}
      - LOCAL_GROUP_ID=id -g ${USER}
      - LOCAL_GROUP_NAME=id -gn ${USER}
    command: bash -c "source /ws/devel/setup.bash && rosrun frida_task_manager receptionist_task_manager.py"