#goal definition
string[] target_objects
int32 waiting_time
---
#result definition
bool result
int32 label
string labelText
float32 score
float32 ymin
float32 xmin
float32 ymax
float32 xmax
geometry_msgs/PointStamped point3D
---
#feedback
string status